shadowsocks/shadowsocks-android

- README.md
add export ANDROID_NDK_HOME variable
> add export ANDROID_NDK_HOME variable

- src/main/AndroidManifest.xml
- src/main/scala/com/github/shadowsocks/AppManager.scala
I'm lazy to figure out how to compile it, and I've only used Scala once before... so please DO review the changes. Thanks. ;-)
> Providing up navigation

- src/main/scala/com/github/shadowsocks/Shadowsocks.scala
Method name should conform to the standard
> Fix a coding style issue

- build.sh
- project/plugins.sbt
- src/main/java/com/github/shadowsocks/System.java
- src/main/jni/Android.mk
- src/main/jni/badvpn/tun2socks/tun2socks.c
- src/main/jni/libancillary/API
- src/main/jni/libancillary/COPYING
- src/main/jni/libancillary/Makefile
- src/main/jni/libancillary/ancillary.h
- src/main/jni/libancillary/fd_recv.c
- src/main/jni/libancillary/fd_send.c
- src/main/jni/libancillary/test.c
- src/main/jni/system.cpp
- src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
Try to avoid issues on some "not that AOSP" devices.
> Pass the file descriptor through unix domain socket

- build.sh
- src/main/AndroidManifest.xml
- src/main/java/com/github/shadowsocks/System.java
- src/main/jni/Android.mk
- src/main/jni/system.cpp
- src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksVpnThread.scala
Provide "protect" socket feature to shadowsocks-libev
> Improve the compatibility by using IPC

- build.sbt
- src/main/AndroidManifest.xml
- src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
- src/main/scala/com/github/shadowsocks/utils/Utils.scala
There's still one issue left: `net.simonvt.menudrawer`. I might redesign the UI for this...
> Migrate to Android 6.0 (1)

- build.sbt
- src/main/scala/com/github/shadowsocks/AppManager.scala
- src/main/scala/com/github/shadowsocks/BaseService.scala
- src/main/scala/com/github/shadowsocks/ParserActivity.scala
- src/main/scala/com/github/shadowsocks/Shadowsocks.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksApplication.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksRunnerActivity.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksVpnThread.scala
- src/main/scala/com/github/shadowsocks/database/MenuAdapter.scala
- src/main/scala/com/github/shadowsocks/database/ProfileManager.scala
- src/main/scala/com/github/shadowsocks/utils/ConfigUtils.scala
- src/main/scala/com/github/shadowsocks/utils/Console.scala
- src/main/scala/com/github/shadowsocks/utils/Parser.scala
- src/main/scala/com/github/shadowsocks/utils/Utils.scala
I'm just messing around... :-P
> SAM (Scala 2.11.7)

- src/main/res/values/strings.xml
- src/main/res/xml/pref_all.xml
- src/main/scala/com/github/shadowsocks/Shadowsocks.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksSettings.scala
- src/main/scala/com/github/shadowsocks/utils/Constants.scala
What do you think of this order?
> Adjust preference order

- src/main/AndroidManifest.xml
- src/main/res/xml/pref_all.xml
- src/main/scala/com/github/shadowsocks/ParserActivity.scala
- src/main/scala/com/github/shadowsocks/ProfileManagerActivity.scala
- src/main/scala/com/github/shadowsocks/Shadowsocks.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksApplication.scala
- src/main/scala/com/github/shadowsocks/database/ProfileManager.scala
- src/main/scala/com/github/shadowsocks/preferences/NatSwitchPreference.scala
I just realized I removed the "Default" profile in the previous PR. So I added it back. And it will be added as soon as the profile list is empty.
Oh and adview will be added as soon as that profile gets picked. LOL
Also fixed some other things...
> Some fixes

- src/main/scala/com/github/shadowsocks/BaseService.scala
- src/main/scala/com/github/shadowsocks/ParserActivity.scala
- src/main/scala/com/github/shadowsocks/ProfileManagerActivity.scala
- src/main/scala/com/github/shadowsocks/Shadowsocks.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksSettings.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
- src/main/scala/com/github/shadowsocks/utils/TrafficMonitor.scala
- src/main/scala/com/github/shadowsocks/utils/TrafficMonitorThread.scala
The current display is 1000x smaller. (my bad)
> Fix rate display

- build.sbt
- src/main/AndroidManifest.xml
- src/main/res/layout/layout_tasker.xml
- src/main/res/values-zh/strings.xml
- src/main/res/values/strings.xml
- src/main/scala/com/github/shadowsocks/TaskerActivity.scala
- src/main/scala/com/github/shadowsocks/TaskerReceiver.scala
- src/main/scala/com/github/shadowsocks/helper/TaskerSettings.scala
- src/main/scala/com/github/shadowsocks/utils/Utils.scala
Support automation app(Tasker, Locale) to turn on/off service.
I will add more feature(such as import profile, switch profile) if this PR is acceptable.
> Automation app integration

- project/build.properties
- project/plugins.sbt
- src/main/AndroidManifest.xml
- src/main/res/values-zh/strings.xml
- src/main/res/values/strings.xml
- src/main/scala/com/github/shadowsocks/AppManager.scala
- src/main/scala/com/github/shadowsocks/AppManagerReceiver.scala
- src/main/scala/com/github/shadowsocks/ServiceBoundContext.scala
- src/main/scala/com/github/shadowsocks/Shadowsocks.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksNotification.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksReceiver.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksSettings.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
- src/main/scala/com/github/shadowsocks/helper/TaskerSettings.scala
> Cache proxied apps for even better performance

- src/main/res/values-zh/strings.xml
- src/main/res/values/strings.xml
- src/main/scala/com/github/shadowsocks/Shadowsocks.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksSettings.scala
- src/main/scala/com/github/shadowsocks/utils/CloseUtils.scala
I also added a useful util: `CloseUtils`, just for my own convenience.
> Fix #479 (HTTP client test)

- src/main/aidl/com/github/shadowsocks/aidl/IShadowsocksServiceCallback.aidl
- src/main/scala/com/github/shadowsocks/BaseService.scala
- src/main/scala/com/github/shadowsocks/ProfileManagerActivity.scala
- src/main/scala/com/github/shadowsocks/Shadowsocks.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksNotification.scala
- src/main/scala/com/github/shadowsocks/utils/TrafficMonitor.scala
Fix #495.
P.S. This creates a little additional battery usage when the UI is active in the foreground which shouldn't be a serious issue.
> Fix dynamic traffic stat in profile selector

- src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
正在连接时点击返回，等会重新打开app界面不刷新的问题。对比了一下ShadowsocksVpnService.scala中的代码。
> 修正正在连接时点击返回，重新打开app界面不刷新的问题。

- build.sbt
- src/main/res/drawable-anydpi-v21/ic_cloud.xml
- src/main/res/drawable-anydpi-v21/ic_cloud_off.xml
- src/main/res/drawable-anydpi-v21/ic_cloud_queue.xml
- src/main/res/layout/status_pref.xml
- src/main/res/values-zh/strings.xml
- src/main/res/values/strings.xml
- src/main/res/xml/pref_all.xml
- src/main/scala/com/github/shadowsocks/Shadowsocks.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksSettings.scala
- src/main/scala/com/github/shadowsocks/preferences/StatusPreference.scala
I think it is pretty close to #508 now.
> Refine layout of StatusPreference

- src/main/res/values-v21/strings.xml
- src/main/res/values-zh-v21/strings.xml
- src/main/res/values-zh/strings.xml
- src/main/res/values/strings.xml
- src/main/scala/com/github/shadowsocks/ProfileManagerActivity.scala
- src/main/scala/com/github/shadowsocks/Shadowsocks.scala
- src/main/scala/com/github/shadowsocks/TaskerActivity.scala
See commit log for detailed info.
> General enhancements

- src/main/scala/com/github/shadowsocks/ShadowsocksDeathRecipient.scala
- src/main/scala/com/github/shadowsocks/utils/ProcessUtils.scala
> Fix a issue in ProcessUtils

- src/main/res/menu/app_manager_menu.xml
- src/main/res/menu/profile_manager_menu.xml
- src/main/res/values-zh/strings.xml
- src/main/res/values/strings.xml
- src/main/scala/com/github/shadowsocks/AppManager.scala
- src/main/scala/com/github/shadowsocks/ParserActivity.scala
- src/main/scala/com/github/shadowsocks/ProfileManagerActivity.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksNotification.scala
- src/main/scala/com/github/shadowsocks/utils/Constants.scala
- src/main/scala/com/github/shadowsocks/utils/Parser.scala
> Import/export one/all ss urls

- src/main/AndroidManifest.xml
- src/main/res/layout/layout_profiles_item.xml
- src/main/res/values-zh/strings.xml
- src/main/res/values/strings.xml
- src/main/scala/com/github/shadowsocks/ParserActivity.scala
- src/main/scala/com/github/shadowsocks/ProfileManagerActivity.scala
The old setMessage(profiles.mkString("\n")) made profiles iterator point to end before it being use.
Use Android Beam or NFC tag to add profile.
> Fix parser bug, add share profile by NFC.

- src/main/scala/com/github/shadowsocks/database/Profile.scala
- src/main/scala/com/github/shadowsocks/utils/Parser.scala
This commit implements the new ss protocol proposed here: https://github.com/shadowsocks/shadowsocks-org/issues/16
> Support one-time authentication in ss urls for sharing

- src/main/res/values-ru/strings.xml
Created russian localisation file shadowsocks-android/src/main/res/values-ru/strings.xml
> Add russian localisation

- src/main/res/values-ru/strings.xml
Fixed mistake in string number 9
> Fixed string number 9

- src/main/res/values-zh-rCN/strings.xml
- src/main/res/values-zh/strings.xml
Most of guys does not know export to where.
> Improve translations for export toast

- .gitignore
- build.sbt
- build.sh
- project/plugins.sbt
- src/main/AndroidManifest.xml
- src/main/res/values-ru/strings.xml
- src/main/res/values-zh-rCN/strings.xml
- src/main/res/values-zh/strings.xml
- src/main/res/values/strings.xml
- src/main/res/xml/pref_all.xml
- src/main/scala/com/github/shadowsocks/Shadowsocks.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksSettings.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
- src/main/scala/com/github/shadowsocks/database/DBHelper.scala
- src/main/scala/com/github/shadowsocks/database/Profile.scala
- src/main/scala/com/github/shadowsocks/utils/Constants.scala
Add KCP support for shadowsocks.
KCPTUN should be setup on a different port to avoid conflicts with Shadowsocks' UDP support.
> Add KCP support

- src/main/assets/pages/about.html
Signed-off-by: Syrone Wong <wong.syrone@gmail.com>
> Fix kcptun license in about page

- build.sh
Should use the `rm -rf` command to remove a directory.
> Fix remove problem

- src/main/res/values-ru/strings.xml
- src/main/res/values-zh-rCN/strings.xml
- src/main/res/values-zh/strings.xml
- src/main/res/values/strings.xml
- src/main/res/xml/pref_all.xml
- src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksSettings.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
- src/main/scala/com/github/shadowsocks/utils/TcpFastOpen.scala
- src/main/scala/com/github/shadowsocks/utils/Utils.scala
TODO: `/etc/init.d` isn't supported by most custom ROMs but not all the devices. For example, Android emulator doesn't support `/etc/init.d`. Maybe some better approach to solve this?
> Add support for TCP Fast Open

- src/main/scala/com/github/shadowsocks/Shadowsocks.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksApplication.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksSettings.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
- src/main/scala/com/github/shadowsocks/ShadowsocksVpnThread.scala
- src/main/scala/com/github/shadowsocks/database/ProfileManager.scala
- src/main/scala/com/github/shadowsocks/utils/TrafficMonitorThread.scala
- src/main/scala/com/github/shadowsocks/utils/Utils.scala
Track the exceptions that might be useful to track down issues on other devices.
> Track caught exceptions

- src/main/res/xml/pref_all.xml
- src/main/scala/com/github/shadowsocks/preferences/KcpCliPreference.scala
> Add help for kcpcli

- kcptun/make.bash
Add session ID support with `--sid` option in the command line.
> KCP with session ID

- .github/issue_template.md
- .github/pull_request_template.md
* Other:
* Add a new PR template as shown here.
* Refine issue template as shown below.
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!
* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Local port: 1080
* Encrypt method:
* Route:
* KCP Parameters: (leave blank if not enabled)
> Refine GitHub templates

- src/main/res/values-ja/strings.xml
> Change some words

- build.sbt
* [ x ] Bugfix
* Other:
Yeah, "ja" is the correct locale code. 😄
> Fix Japanese translation again

- src/main/res/values-ja/strings.xml
> completed Japanese translation (The vast majority)

- src/main/res/values-ja/strings.xml
* Other:
Revised a wrong translation and alter the wording.
20:15 16/12/2016
> Update Japanese translation

- .github/faq.md
- .github/issue_template.md
- build.sbt
- src/main/res/drawable/ic_action_help_outline.xml
- src/main/res/values-zh-rCN/strings.xml
- src/main/res/values-zh-rTW/strings.xml
- src/main/res/values/strings.xml
- src/main/scala/com/github/shadowsocks/MainActivity.scala
Now that we have the new drawer, it's time to add new sections to it. What about an FAQ section for starters?
> 	Add an FAQ section in drawer

- src/main/res/values-zh-rTW/strings.xml
- src/main/res/values/strings.xml
> Update translation for Traditional Chinese

- .travis.yml
- build.sbt
Signed-off-by: Syrone Wong <wong.syrone@gmail.com>
* Other:
> Speed up ndk-build from sbt-android

- .travis.yml
- build.sbt
Reverts shadowsocks/shadowsocks-android#1070
> Revert "Speed up ndk-build from sbt-android"

- mobile/src/main/scala/com/github/shadowsocks/BaseService.scala
- mobile/src/main/scala/com/github/shadowsocks/GuardedProcess.scala
- mobile/src/main/scala/com/github/shadowsocks/ShadowsocksApplication.scala
- mobile/src/main/scala/com/github/shadowsocks/ShadowsocksBackupAgent.scala
- mobile/src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
- mobile/src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
- mobile/src/main/scala/com/github/shadowsocks/ShadowsocksVpnThread.scala
- mobile/src/main/scala/com/github/shadowsocks/acl/Acl.scala
- mobile/src/main/scala/com/github/shadowsocks/acl/AclSyncJob.scala
- mobile/src/main/scala/com/github/shadowsocks/utils/IOUtils.scala
- mobile/src/main/scala/com/github/shadowsocks/utils/TcpFastOpen.scala
- mobile/src/main/scala/com/github/shadowsocks/utils/TrafficMonitorThread.scala
- mobile/src/main/scala/com/github/shadowsocks/utils/Utils.scala
* Other:
It looks nicer.
Other changes btw:
* Removes duplicated logcats from GuardedProcess;
* local_port is moved to command line options since that's not sensitive;
* pdnsd uses cache dir;
* Refinements to Utils.
`shadowsocks-libev` is updated. Merge `no-prefix` branch if this gets merged.
> Move config files to files directory

- .gitmodules
- mobile/src/main/jni/Android.mk
- mobile/src/main/res/values/arrays.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/pref_profile.xml
- mobile/src/main/scala/com/github/shadowsocks/BaseService.scala
- mobile/src/main/scala/com/github/shadowsocks/database/DBHelper.scala
- mobile/src/main/scala/com/github/shadowsocks/database/Profile.scala
- mobile/src/main/scala/com/github/shadowsocks/utils/Constants.scala
- mobile/src/main/scala/com/github/shadowsocks/utils/Parser.scala
* Other:
See commit logs for details.
> Implement SIP004, SIP002

- mobile/src/main/res/values/arrays.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/scala/com/github/shadowsocks/BaseService.scala
- mobile/src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
- mobile/src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
- mobile/src/main/scala/com/github/shadowsocks/acl/Acl.scala
- mobile/src/main/scala/com/github/shadowsocks/acl/CustomRulesFragment.scala
* A cleaner format;
* Provides better behavior when importing a non-compatible ACL;
* Supports importing URL from a imported file with up to 10 layers.
> Rewrite network ACLs

- mobile/src/main/scala/com/github/shadowsocks/MainActivity.scala
> fix fragment called twice

- core/build.gradle
- core/src/overture/make.bat
Signed-off-by: forDream <gam2046@users.noreply.github.com>
* Other:
- Supports building projects on windows.
- Python is required
> Fix building with Windows. #1684

- mobile/src/main/res/drawable-v26/ic_qu_camera_foreground.xml
- mobile/src/main/res/drawable-v26/ic_qu_camera_launcher.xml
- mobile/src/main/res/drawable-v26/ic_qu_shadowsocks_foreground.xml
- mobile/src/main/res/drawable-v26/ic_qu_shadowsocks_launcher.xml
- mobile/src/main/res/values/colors.xml
* Other:
Adaptive icon also support app shortcuts
> add adaptive shortcut icon for android 8.0+

- core/src/overture/make.bat
* [x ] Bugfix
* Other:
Install toolchains in core/src/overture/.deps before checking gcc.
> Fix windows building issues

- .travis.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- mobile/build.gradle
* Other:
just updated build-tools, some dependencies, and kotlin, and also gradle
> updated things

- mobile/src/main/java/com/github/shadowsocks/MainActivity.kt
> Fix night mode

- .travis.yml
- gradle.properties
- Enable android build cache
- Increase jvmargs to 2G
> speed up for gradle

- core/src/main/java/com/github/shadowsocks/bg/BaseService.kt
According to [the Internet](https://stackoverflow.com/q/20330355/2245107), Handler is better than TimerTask.
Test: Built and run on Android 9.
> Replace TimerTask with Handler

- build.gradle
- plugin/build.gradle
With a snapshot AAR from self hosted maven repo.
> Fix bottom app bar

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
> Officially support Chrome OS

- core/schemas/com.github.shadowsocks.database.PrivateDatabase/28.json
- core/src/androidTest/java/com/github/shadowsocks/database/MigrationTest.kt
- core/src/main/java/com/github/shadowsocks/bg/VpnService.kt
- core/src/main/java/com/github/shadowsocks/database/PrivateDatabase.kt
- core/src/main/java/com/github/shadowsocks/database/Profile.kt
- core/src/main/java/com/github/shadowsocks/utils/Constants.kt
- core/src/main/res/values/strings.xml
- mobile/src/main/java/com/github/shadowsocks/ProfileConfigFragment.kt
- mobile/src/main/res/drawable/ic_device_data_usage.xml
- mobile/src/main/res/xml/pref_profile.xml
This is an [Android Q new feature](https://developer.android.com/reference/android/net/VpnService.Builder.html#setMetered(boolean)) but it can be backported to Android 9 using a hack. Adaptation for Android Q will be added to `q-beta` branch.
> Support metered hint on Android 9+

- CONTRIBUTING.md
- README.md
I am a new user to this project who was initially confused on how I could get involved.  I made some changes that hopefully will help others get involved too.  Please let me know if you disagree with the updates that I've made.
> Clarifying instruction documents

- core/src/main/java/com/github/shadowsocks/utils/Utils.kt
- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/com/github/shadowsocks/AppManager.kt
- mobile/src/main/java/com/github/shadowsocks/ProfileConfigActivity.kt
- mobile/src/main/java/com/github/shadowsocks/ProfileConfigFragment.kt
- mobile/src/main/java/com/github/shadowsocks/UdpFallbackProfileActivity.kt
- mobile/src/main/java/com/github/shadowsocks/tasker/ConfigActivity.kt
- mobile/src/main/res/layout/layout_apps.xml
- mobile/src/main/res/layout/layout_main.xml
- mobile/src/main/res/layout/layout_tasker.xml
- mobile/src/main/res/layout/layout_udp_fallback.xml
- mobile/src/main/res/values/styles.xml
- plugin/src/main/res/values/styles.xml
> Immersive theme: Make navigation bars translucent

- plugin/CHANGES.md
- plugin/gradle.properties
- plugin/src/main/AndroidManifest.xml
Read commit messages for more information.
> Plugin lib 1.3.1

- build.gradle
- core/build.gradle
- mobile/build.gradle
- mobile/src/main/java/com/github/shadowsocks/widget/StatsBar.kt
- mobile/src/main/res/values/dimen.xml
- tv/src/main/java/com/github/shadowsocks/tv/MainPreferenceFragment.kt
Finally I finish the original vision in #1027.
Slight issue: You can see stats bar sliding down after `onCreate`.
> Show stats bar only when connected

- core/src/main/java/com/github/shadowsocks/bg/VpnService.kt
Related bug: https://issuetracker.google.com/issues/149636790
> Workaround for #2361

- core/build.gradle.kts
- core/src/main/java/com/github/shadowsocks/UrlImportActivity.kt
- mobile/src/main/java/com/github/shadowsocks/ProfileConfigActivity.kt
- mobile/src/main/java/com/github/shadowsocks/ProfileConfigFragment.kt
- mobile/src/main/java/com/github/shadowsocks/acl/CustomRulesFragment.kt
- mobile/src/main/java/com/github/shadowsocks/preference/PluginPreferenceDialogFragment.kt
- mobile/src/main/java/com/github/shadowsocks/subscription/SubscriptionFragment.kt
- plugin/CHANGES.md
- plugin/build.gradle.kts
- plugin/gradle.properties
- plugin/src/main/AndroidManifest.xml
- plugin/src/main/java/com/github/shadowsocks/plugin/fragment/AlertDialogFragment.kt
- plugin/src/main/java/com/github/shadowsocks/plugin/fragment/Utils.kt
- tv/src/main/java/com/github/shadowsocks/tv/MainFragment.kt
- tv/src/main/java/com/github/shadowsocks/tv/MainPreferenceFragment.kt
- tv/src/main/java/com/github/shadowsocks/tv/ProfilesDialogFragment.kt
Needs more testing. Main change is using new fragment result API from androidx.fragment 1.3.
> Plugin 2.0.1

- mobile/src/main/java/com/github/shadowsocks/MainActivity.kt
- mobile/src/main/java/com/github/shadowsocks/widget/FabProgressBehavior.kt
- mobile/src/main/java/com/github/shadowsocks/widget/ServiceButton.kt
- mobile/src/main/res/layout/layout_main.xml
New sick animation using `CircularProgressIndicator`. Further improvements are definitely possible. :)
> Add progress indicator to ServiceButton

- buildSrc/src/main/kotlin/Helpers.kt
- core/build.gradle.kts
- core/src/main/AndroidManifest.xml
- core/src/main/java/com/github/shadowsocks/Core.kt
- core/src/main/java/com/github/shadowsocks/bg/ServiceNotification.kt
- core/src/main/java/com/github/shadowsocks/bg/VpnService.kt
- core/src/main/java/com/github/shadowsocks/net/DefaultNetworkListener.kt
- core/src/main/java/com/github/shadowsocks/subscription/SubscriptionService.kt
- mobile/src/main/AndroidManifest.xml
- tv/src/main/AndroidManifest.xml
> Target Android 12

- .circleci/config.yml
- buildSrc/src/main/kotlin/Helpers.kt
Reverts shadowsocks/shadowsocks-android#3119
> Revert "Update shadowsocks-rust"

- core/src/main/jni/Android.mk
These two directories don't exist.
> Remove non-exist include dirs
