shadowsocks/shadowsocks-android

build.sbt
project/build.properties
project/plugins.sbt

1. Update sbt-android-pluin to enable multidex support and other bug fixes
2. Update sbt to 0.13.8 to support jcenter resolver, which will speed up dependency resolving according to google.

Update sbt and sbt-android-plugin

---

README.md

it might be due to the upstream changes. 
with the sdk and ndk version listed it can not be built successfully 
even with google service and other extra packages installed.
update it to my working versions.

 update dependency versions

---

src/main/jni/badvpn/tun2socks/tun2socks.c

Turn on TCP_NODELAY for TCP sockets in lwIP stack.
Notice: I haven't tested on Android yet.

add tcp_nagle_disable in tun2socks

---

README.md
gfwlist/gen.py
src/main/assets/pages/about.html
src/main/res/values/arrays.xml
src/main/res/values/chnroute.xml
src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
src/main/scala/com/github/shadowsocks/database/DBHelper.scala
src/main/scala/com/github/shadowsocks/utils/Constants.scala

Fix #569.
It could have worked without upgrading database by using an option called `bypass-china-only`. But I think we will get better readability this way.

Add option: bypass China only

---

src/main/scala/com/github/shadowsocks/package.scala

`Future.onFailure` has been deprecated since scala 2.12, let's use `Future.onComplete` instead.
In `scala.concurrent.Future`:
```
@deprecated("use `onComplete` or `failed.foreach` instead (keep in mind that they take total rather than partial functions)", "2.12")
def onFailure[U](@deprecatedName('callback) pf: PartialFunction[Throwable, U])(implicit executor: ExecutionContext): Unit = onComplete {
case Failure(t) =>
pf.applyOrElse[Throwable, Any](t, Predef.conforms[Throwable]) // Exploiting the cached function to avoid MatchError
case _ =>
}
```

Replace Future.onFailure with Future.onComplete

---

src/main/scala/com/github/shadowsocks/ServiceBoundContext.scala
src/main/scala/com/github/shadowsocks/Shadowsocks.scala
src/main/scala/com/github/shadowsocks/ShadowsocksDeathRecipient.scala
src/main/scala/com/github/shadowsocks/utils/IOUtils.scala
src/main/scala/com/github/shadowsocks/utils/ProcessUtils.scala

If **shadowsocks:vpn** died unexpected, such as:
```bash
> adb shell ps | grep shadowsocks
u0_a52    1456  141   537172 40864 ffffffff b754e7ca S com.github.shadowsocks
u0_a52    1477  141   523808 32712 ffffffff b754ff37 S com.github.shadowsocks:vpn
u0_a52    1523  1477  6980   1424  c01d7f5f b7df5f37 S /data/data/com.github.shadowsocks/ss-local
u0_a52    1524  1477  8508   1236  ffffffff b7df577f S /data/data/com.github.shadowsocks/pdnsd
u0_a52    1525  1477  6960   1420  c01d7f5f b7df5f37 S /data/data/com.github.shadowsocks/ss-tunnel
u0_a52    1533  1477  6488   1180  c01d7f5f b7df5f37 S /data/data/com.github.shadowsocks/tun2socks
```
```bash
> adb shell kill 1477
```
We'll find **shadowsocks** won't respond to `trafficUpdated` or `stateChanged` no matter how many times we click on …

Fix binder ipc issue when process died unexpected

---

src/main/aidl/com/github/shadowsocks/aidl/IShadowsocksService.aidl
src/main/scala/com/github/shadowsocks/BaseService.scala
src/main/scala/com/github/shadowsocks/Shadowsocks.scala
src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
src/main/scala/com/github/shadowsocks/ShadowsocksQuickSwitchActivity.scala
src/main/scala/com/github/shadowsocks/ShadowsocksRunnerActivity.scala
src/main/scala/com/github/shadowsocks/ShadowsocksRunnerService.scala
src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
src/main/scala/com/github/shadowsocks/ShadowsocksVpnThread.scala
src/main/scala/com/github/shadowsocks/TaskerReceiver.scala
src/main/scala/com/github/shadowsocks/utils/Constants.scala
src/main/scala/com/github/shadowsocks/utils/TrafficMonitor.scala
src/main/scala/com/github/shadowsocks/utils/Utils.scala

`start(Config)` and `stop()` has been replaced by `use(Config)` and `use(null)` to implement this feature. Invoking `start(Config)` with a different config will restart the service.
There are three ways to switch profiles which is when service restart is required:
1. via Profile selector.
2. via Tasker.
3. via Quick Switch introduced in #598.
When the latter two are performed and `Shadowsocks` is resumed, it will sometimes start the service twice and after a chain of events it results in `Unable to connect to remote server` so the service stops itself.

Automatic service restart (with zero latency) after switching profile

---

src/main/AndroidManifest.xml
src/main/res/layout/layout_apps.xml
src/main/res/layout/layout_apps_item.xml
src/main/res/layout/layout_profiles_item.xml
src/main/res/layout/overlay.xml
src/main/res/values-zh-rCN/strings.xml
src/main/res/values-zh-rTW/strings.xml
src/main/res/values/strings.xml
src/main/scala/com/github/shadowsocks/AppManager.scala
src/main/scala/com/github/shadowsocks/ProfileManagerActivity.scala
src/main/scala/com/github/shadowsocks/Shadowsocks.scala

This commit adds an app banner in Android TV and introduces several changes including refactoring AppManager to make all features accessible with D-pad navigation.
Currently this app has the exact same user interface on Android TV as on normal Android devices but one should create a TV-specific user interface in the future.
P.S. Only tested in Android emulator. More testing might be needed.
Screenshots attached.

Add support for Android TV

---

gfwlist/gen.pl

The perl version takes two seconds while the python version takes more than 30 seconds
Usage: perl ./gen.pl < chnroute.txt > chnroute-merged.txt
Signed-off-by: Syrone Wong <wong.syrone@gmail.com>

add a perl script to generate chnroute

---

src/main/jni/Android.mk

[info] Android NDK: WARNING:jni/Android.mk:mbedtls: LOCAL_LDLIBS is always ignored for static libraries

Drop redundant rule

---

build.sh
kcptun/make.bash
src/main/AndroidManifest.xml
src/main/java/com/github/shadowsocks/System.java
src/main/jni/Android.mk
src/main/jni/build-shared-executable.mk
src/main/jni/system.cpp
src/main/scala/com/github/shadowsocks/MainActivity.scala
src/main/scala/com/github/shadowsocks/ShadowsocksApplication.scala
src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala
src/main/scala/com/github/shadowsocks/preferences/KcpCliPreferenceDialogFragment.scala
src/main/scala/com/github/shadowsocks/utils/Constants.scala

* Other:
Advantage:
* No more worries about inconsistencies about native libraries and extracting them (therefore no more ETXTBSY errors);
* Native libraries are counted in App section instead of Data section in storage information.
Disadvantage:
* Executable names have to be `lib*.so` otherwise Android system won't extract it.

Let Android system extract native libraries

---

.jvmopts

* Other:
The `MaxPermSize` param was removed in JDK 1.8

MaxPermSize was removed in JDK 1.8

---

mobile/src/main/scala/com/github/shadowsocks/BaseService.scala
mobile/src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala
mobile/src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala

* Other:
Add secondary remote dns support:
192.168.1.1,192.168.1.2
Overture config example:
`{"BindAddress":":1133","RedirectIPv6Record":true,"DomainBase64Decode":true,"HostsFile":"hosts","MinimumTTL":3600,"CacheSize":4096,"PrimaryDNS":[{"Name":"Primary-1","Address":"119.29.29.29:53","Timeout":6,"EDNSClientSubnet":{"Policy":"disable"},"Protocol":"udp"},{"Name":"Primary-2","Address":"114.114.114.114:53","Timeout":6,"EDNSClientSubnet":{"Policy":"disable"},"Protocol":"udp"}],"AlternativeDNS":[{"Name":"8.8.8.8","Address":"8.8.8.8:53","Timeout":6,"EDNSClientSubnet":{"Policy":"disable"},"Protocol":"tcp","Socks5Address":"127.0.0.1:1080"},{"Name":"8.8.4.4","Address":"8.8.4.4:53","Timeout":6,"EDNSClientSubnet":{"Policy":"disable"},"Protocol":"tcp","Socks5Ad …

Add multiple remote dns support. Remove alternative dns in global mode.

---

build.sbt

* Other:
Keeps overall abi consistent with `mobile/src/main/jni/Application.mk` and `mobile/src/overture/make.bash`
If any future library dependencies come with extra abis, say `x64/foo.so`, the x64 abi will be packaged into the final apk.
Therefore, the `lib` folder of the apk will look like:
```
armeabi-v7a/foo.so
armeabi-v7a/others.so
arm64-v8a/foo.so
arm64-v8a/others.so
x86/foo.so
x86/others.so
x64/foo.so
```
If the apk is installed into a x64 android phone, `x64/others.so` cannot be found and the program may crash.
Adding `ndkAbiFilter` ensures that only defined abis are included into the apk.

Limit abi for consistency

---

.travis.yml
README.md
mobile/src/main/jni/Android.mk
mobile/src/main/jni/Application.mk

Signed-off-by: Syrone Wong <wong.syrone@gmail.com>
* Other:

minor improvements starting from NDK r16 (#1458)

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/java/com/evernote/android/job/JobConstants.kt
mobile/src/main/java/com/github/shadowsocks/App.kt
mobile/src/main/java/com/github/shadowsocks/AppManager.kt
mobile/src/main/java/com/github/shadowsocks/BootReceiver.kt
mobile/src/main/java/com/github/shadowsocks/ConfigBackupHelper.kt
mobile/src/main/java/com/github/shadowsocks/GlobalSettingsPreferenceFragment.kt
mobile/src/main/java/com/github/shadowsocks/MainActivity.kt
mobile/src/main/java/com/github/shadowsocks/ProfileConfigFragment.kt
mobile/src/main/java/com/github/shadowsocks/acl/Acl.kt
mobile/src/main/java/com/github/shadowsocks/bg/BaseService.kt
mobile/src/main/java/com/github/shadowsocks/bg/Executable.kt
mobile/src/main/java/com/github/shadowsocks/bg/GuardedProcess.kt
mobile/src/main/java/com/github/shadowsocks/bg/LocalDnsService.kt
mobile/src/main/java/com/github/shadowsocks/bg/TrafficMonitorThread.kt
mobile/src/main/java/com/github/shadowsocks/bg/TransproxyService.kt
mobile/src/main/java/com/github/shadowsocks/bg/VpnService.kt
mobile/src/main/java/com/github/shadowsocks/database/PrivateDatabase.kt
mobile/src/main/java/com/github/shadowsocks/database/Profile.kt
mobile/src/main/java/com/github/shadowsocks/database/ProfileManager.kt
mobile/src/main/java/com/github/shadowsocks/database/PublicDatabase.kt
mobile/src/main/java/com/github/shadowsocks/plugin/PluginManager.kt
mobile/src/main/java/com/github/shadowsocks/preference/DataStore.kt
mobile/src/main/java/com/github/shadowsocks/preference/OrmLitePreferenceDataStore.kt
mobile/src/main/java/com/github/shadowsocks/utils/DeviceContext.kt
mobile/src/main/java/com/github/shadowsocks/utils/DirectBoot.kt
mobile/src/main/java/com/github/shadowsocks/utils/TcpFastOpen.kt
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/backup_descriptor.xml
mobile/src/main/res/xml/pref_global.xml

To do direct boot, important files need to be moved to device storage (i.e. not as safe storage). The only thing sensitive is user credentials (server settings in each profile) and the config file passed to libss-*.so. In order to implement direct boot, at least the active profile has to be moved/copied to device storage.
This commit keeps profile information (and temporary data used by ProfileConfigFragment) and Shadowsocks config in credential storage and move everything else to device storage. In order to make direct boot work, active profile is also copied into device storage and Shadowsocks config file is created in device storage during direct boot. Cleanup of those information is also implemented.
Fixes #1457.
NB:
* `android:directBootAware` can't be used on application element. …

Implement direct boot awareness

---

core/src/overture/make.bat

* Other:
make.bat not detect Windows go binary due to missing '.exe' of filename
when the script convert from bash to bat.

Fix Windows build script of overture

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/java/com/github/shadowsocks/bg/VpnService.kt

* Other:
This pull request uses `setUnderlyingNetwork` not only as a hint, but also uses the underlying network it sets for VPN connections.
Everything seems to be working fine. Might need more testing.
This also fixes #1666.

Actually use underlying network

---

mobile/src/main/java/com/github/shadowsocks/bg/BaseService.kt
mobile/src/main/java/com/github/shadowsocks/bg/GuardedProcessPool.kt
mobile/src/main/java/com/github/shadowsocks/bg/LocalDnsService.kt
mobile/src/main/java/com/github/shadowsocks/bg/TransproxyService.kt
mobile/src/main/java/com/github/shadowsocks/bg/VpnService.kt

This way we can destroy the processes and wait for them to exit in parallel, and ensure the process is destroyed so that we won't encounter strange port being used issue at the same time.
This addresses #1740 but probably doesn't fix it.

Manage all processes with GuardedProcessPool

---

mobile/src/main/java/com/github/shadowsocks/MainActivity.kt
mobile/src/main/java/com/github/shadowsocks/preference/DataStore.kt
mobile/src/main/java/com/github/shadowsocks/utils/Constants.kt
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/pref_global.xml

* Other:
When SS is used in China as a pure secure proxy, the hardcoded connection test Google server may not work.
Here I added two global URL configuration, one for China List mode, one for else.

make connection test url configurable

---

mobile/src/main/java/com/github/shadowsocks/MainActivity.kt
mobile/src/main/java/com/github/shadowsocks/preference/DataStore.kt
mobile/src/main/java/com/github/shadowsocks/utils/Constants.kt
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/pref_global.xml

Reverts shadowsocks/shadowsocks-android#1762.
This extra option
* kills off a feature;
* creates extra work for translator;
* is completely useless anyway.

Revert "make connection test url configurable"

---

mobile/src/main/java/com/github/shadowsocks/App.kt
mobile/src/main/java/com/github/shadowsocks/GlobalSettingsPreferenceFragment.kt
mobile/src/main/java/com/github/shadowsocks/MainActivity.kt
mobile/src/main/java/com/github/shadowsocks/ProfileConfigFragment.kt
mobile/src/main/java/com/github/shadowsocks/preference/DataStore.kt
mobile/src/main/java/com/github/shadowsocks/utils/Constants.kt
mobile/src/main/java/com/github/shadowsocks/utils/Utils.kt
mobile/src/main/res/drawable/ic_image_brightness_3.xml
mobile/src/main/res/values/arrays.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/pref_global.xml
plugin/src/main/java/com/github/shadowsocks/plugin/OptionsCapableActivity.kt
plugin/src/main/java/com/github/shadowsocks/plugin/PluginContract.kt

It seems that Android 9.0 has finally supported Night mode officially. Unfortunately it doesn't work on emulator (not on my side) so I'm not sure if this works.
@onlymash Please review.

Remove night mode switch

---

mobile/src/main/java/com/github/shadowsocks/ProfileConfigFragment.kt
mobile/src/main/res/xml/pref_profile.xml
plugin/CHANGES.md
plugin/build.gradle
plugin/src/main/java/com/github/shadowsocks/plugin/PluginOptions.kt
plugin/src/test/java/com/github/shadowsocks/plugin/PluginOptionsTest.kt

Okay. Our old `beta`/`develop` branches definitely went nowhere. Let's just replace `beta` with feature PRs and `develop` with PRs like this one. In theory we should release an update for plugin lib immediately after merging PRs like this one.

Plugin library 1.1.0

---

README.md

Google Play Store on TV does not offer the option to opt in to beta AFAIC. It might be a good idea to put a link somewhere.

Add links to Google Play beta

---

build.gradle
core/build.gradle
core/src/main/java/com/github/shadowsocks/Core.kt
core/src/main/java/com/github/shadowsocks/aidl/ShadowsocksConnection.kt
core/src/main/java/com/github/shadowsocks/bg/BaseService.kt
core/src/main/java/com/github/shadowsocks/bg/GuardedProcessPool.kt
core/src/main/java/com/github/shadowsocks/bg/LocalDnsService.kt
core/src/main/java/com/github/shadowsocks/bg/LocalSocketListener.kt
core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt
core/src/main/java/com/github/shadowsocks/bg/RemoteConfig.kt
core/src/main/java/com/github/shadowsocks/bg/TrafficMonitor.kt
core/src/main/java/com/github/shadowsocks/bg/TransproxyService.kt
core/src/main/java/com/github/shadowsocks/bg/VpnService.kt
core/src/main/java/com/github/shadowsocks/utils/HttpsTest.kt
core/src/main/java/com/github/shadowsocks/utils/TcpFastOpen.kt
core/src/main/java/com/github/shadowsocks/utils/Utils.kt
mobile/proguard-rules.pro
mobile/src/main/java/com/github/shadowsocks/AppManager.kt
mobile/src/main/java/com/github/shadowsocks/MainActivity.kt
mobile/src/main/res/layout/layout_apps.xml
tv/proguard-rules.pro
tv/src/main/java/com/github/shadowsocks/tv/MainPreferenceFragment.kt

What are coroutines: Basically threads but much more light-weight. `Dispatchers.Main` is implemented using Android's `Handler/Looper` mechanism.
With this PR, most bg work can be done on the main thread, so we have fewer concurrency issues to worry about. Furthermore, sockets are now protected in parallel using IO thread pool and error callbacks are refined. (see commit logs for more info)
This PR also cleans up various IO threads that live longer than that they are supposed to live. Fewer threads = less RAM!
One downside of using coroutines, however, is that debugging deadlocks can be much harder, as dumping stacks aren't useful. This might be mitigated using [kotlinx-coroutines-debug](https://github.com/Kotlin/kotlinx.coroutines/tree/master/core/kotlinx-coroutines-debug) but that needs …

Refactor using coroutines

---

core/src/main/java/com/github/shadowsocks/bg/LocalDnsService.kt
core/src/main/java/com/github/shadowsocks/net/HostsFile.kt
core/src/main/java/com/github/shadowsocks/net/LocalDnsServer.kt
core/src/main/java/com/github/shadowsocks/preference/EditTextPreferenceModifiers.kt
core/src/main/java/com/github/shadowsocks/preference/HostsSummaryProvider.kt
core/src/main/java/com/github/shadowsocks/utils/Constants.kt
core/src/main/java/com/github/shadowsocks/utils/Utils.kt
core/src/main/res/values/strings.xml
mobile/src/main/java/com/github/shadowsocks/GlobalSettingsPreferenceFragment.kt
mobile/src/main/java/com/github/shadowsocks/ProfileConfigFragment.kt
mobile/src/main/java/com/github/shadowsocks/preference/BrowsableEditTextPreferenceDialogFragment.kt
mobile/src/main/res/xml/pref_global.xml
plugin/src/main/res/values/strings.xml
tv/src/main/java/com/github/shadowsocks/tv/MainPreferenceFragment.kt
tv/src/main/res/xml/pref_main.xml

support hosts

---

core/src/main/java/com/github/shadowsocks/database/Profile.kt

Works better under IPv6-only environments.

Use domain name as default value for remoteDns

---

mobile/src/main/res/xml/pref_global.xml

Set a key on the PreferenceScreen if using initialExpandedChildrenCount. 
the state is correctly saved and restored when the configuration changes (such as when rotating the screen).

Add a key to settings screen

---

mobile/src/main/java/com/github/shadowsocks/AppManager.kt

(cherry picked from commit 8306daa8b5f08f6e9c8fd85d03db974ad100caae)
提交修改至上游
1. 显示包括停用（disable）和隐藏（hide）状态的应用。这些状态可能由冰箱等“冻结“省电类应用设置。
2. 排序优先显示用户应用。不管是否为绕过，用户应用与系统应用的代理策略总是差别很大。
3. 应用到所有配置文件时，同步设置分应用开关和绕过状态。找不到不这样做的理由。
4. 去掉了内容奇怪的错误提示，并且几乎不可能发生。

Optimization AppManager UI

---

core/src/main/AndroidManifest.xml
core/src/main/java/com/github/shadowsocks/Core.kt
core/src/main/java/com/github/shadowsocks/bg/BaseService.kt
mobile/src/main/AndroidManifest.xml

Add permission for receiver

---

core/schemas/com.github.shadowsocks.database.PrivateDatabase/29.json
core/src/main/java/com/github/shadowsocks/acl/Acl.kt
core/src/main/java/com/github/shadowsocks/database/PrivateDatabase.kt
core/src/main/java/com/github/shadowsocks/database/Profile.kt
core/src/main/java/com/github/shadowsocks/database/ProfileManager.kt
core/src/main/java/com/github/shadowsocks/net/Subnet.kt
core/src/main/java/com/github/shadowsocks/subscription/Subscription.kt
core/src/main/java/com/github/shadowsocks/utils/Sorters.kt
core/src/main/res/values/strings.xml
mobile/build.gradle
mobile/src/main/java/com/github/shadowsocks/MainActivity.kt
mobile/src/main/java/com/github/shadowsocks/ProfileConfigFragment.kt
mobile/src/main/java/com/github/shadowsocks/ProfilesFragment.kt
mobile/src/main/java/com/github/shadowsocks/subscription/SubscriptionFragment.kt
mobile/src/main/java/com/github/shadowsocks/widget/UndoSnackbarManager.kt
mobile/src/main/res/drawable-night/ic_cloud_queue.xml
mobile/src/main/res/drawable/ic_action_cloud_download.xml
mobile/src/main/res/drawable/ic_cloud_queue.xml
mobile/src/main/res/layout/dialog_subscription.xml
mobile/src/main/res/layout/layout_profile.xml
mobile/src/main/res/layout/layout_subscriptions.xml
mobile/src/main/res/menu/navigation_main.xml
mobile/src/main/res/menu/subscription_menu.xml

Add subscription support

---

build.gradle
core/build.gradle
detekt.yml
mobile/build.gradle
plugin/CHANGES.md
plugin/build.gradle
plugin/gradle.properties
plugin/src/main/AndroidManifest.xml
plugin/src/main/java/com/github/shadowsocks/plugin/OptionsCapableActivity.kt
plugin/src/test/java/com/github/shadowsocks/plugin/PluginOptionsTest.kt
tv/build.gradle

Plugin 1.3.2

---

core/build.gradle
core/src/main/java/com/github/shadowsocks/bg/BaseService.kt
core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt
core/src/main/java/com/github/shadowsocks/database/Profile.kt
core/src/main/java/com/github/shadowsocks/plugin/NativePlugin.kt
core/src/main/java/com/github/shadowsocks/plugin/Plugin.kt
core/src/main/java/com/github/shadowsocks/plugin/PluginConfiguration.kt
core/src/main/java/com/github/shadowsocks/plugin/PluginList.kt
core/src/main/java/com/github/shadowsocks/plugin/PluginManager.kt
core/src/main/java/com/github/shadowsocks/plugin/ResolvedPlugin.kt
core/src/main/res/values/strings.xml
mobile/src/main/java/com/github/shadowsocks/ProfileConfigFragment.kt
mobile/src/main/java/com/github/shadowsocks/preference/PluginPreference.kt
mobile/src/main/java/com/github/shadowsocks/preference/PluginPreferenceDialogFragment.kt
mobile/src/main/res/drawable/ic_action_lock_open.xml
mobile/src/main/res/layout/icon_list_item_2.xml
mobile/src/main/res/values/colors.xml
mobile/src/main/res/xml/pref_profile.xml
plugin/CHANGES.md
plugin/README.md
plugin/build.gradle
plugin/doc.md
plugin/gradle.properties
plugin/src/main/AndroidManifest.xml
plugin/src/main/java/com/github/shadowsocks/plugin/PluginContract.kt

Main change: support plugin aliases proposed by @CzBiX: https://github.com/shadowsocks/v2ray-plugin-android/issues/18#issuecomment-581262267
For other changes, see CHANGES.md.
I have not thoroughly tested this. @madeye Can you help? (client app should not require a plugin lib update)

Plugin 1.3.4

---

core/build.gradle.kts
core/src/main/java/com/github/shadowsocks/utils/Utils.kt
mobile/build.gradle.kts
mobile/src/main/AndroidManifest.xml
mobile/src/main/java/com/github/shadowsocks/ScannerActivity.kt
mobile/src/main/java/com/github/shadowsocks/widget/WindowInsetsListeners.kt
mobile/src/main/res/layout/layout_scanner.xml

Well boys, we did it. Crappy third-party libraries are no more.
We now finally have first-class support for scanning QR codes in-app for Android 6+. With all the trained models bundled inside the apk, we have a (very satisfactory) increase of apk size of 4.5MB.
Fixes #2548.

Migrate to ML kit for scanning QR code

---

core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt
core/src/main/java/com/github/shadowsocks/plugin/PluginManager.kt
plugin/CHANGES.md
plugin/README.md
plugin/gradle.properties
plugin/src/main/AndroidManifest.xml
plugin/src/main/java/com/github/shadowsocks/plugin/PluginContract.kt

@madeye Please help finish this implementation, thanks! You can read `isV2` here: https://github.com/shadowsocks/shadowsocks-android/blob/1783420a89e46c39524e9beeb7a7dac919b36ad0/core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt#L105
Fixes #2576.

Plugin 2.0.0

---

core/src/main/java/com/github/shadowsocks/bg/BaseService.kt

由于"NONE"方法的引入在判断逻辑上做了一点小更改，修复在已经连接状态下直接切换到一个使用“NONE”方法且没有输入密码的配置时服务会停止的问题。

Fix little problem of profile switching

---

core/src/main/java/com/github/shadowsocks/bg/BaseService.kt
core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt
core/src/main/java/com/github/shadowsocks/bg/VpnService.kt
core/src/main/res/values/strings.xml

Fixes #2722. This also allows turning on service without having an Internet connection, even when the server is a domain name. Neat!

Resolve server name dynamically always

---

core/src/main/rust/linker-wrapper.py

fix #2666 #2711
if linker arguments too long, rust will use response file [link.rs#L1178](https://github.com/rust-lang/rust/blob/d44f647ffcff0e1ff2c0f45b6a0ce9796d80f1ca/compiler/rustc_codegen_ssa/src/back/link.rs#L1178), then output filename detect will failed.
Under msys2 and cygwin `RUST_ANDROID_GRADLE_CC` should convert to unix path  when use native python.
Under msys2 and cygwin environment the response file will convert to full arguments when run under winshell, so need convert linker arguments back to response file to avoid `Argument list too long`

Fix windows build failed and allowed build under msys2 or cygwin

---

tv/build.gradle.kts
tv/src/freedom/res/values/styles.xml
tv/src/main/java/com/github/shadowsocks/tv/MainFragment.kt
tv/src/main/res/values/styles.xml

This creates two variants for tv, freedom containing the original design, and google containing one matching Google's nonsense guideline. The former should be published on GitHub and elsewhere.
**Needs testing**.

Bring back semitransparent TV app via build variants

---

core/src/main/assets/acl/bypass-china.acl
core/src/main/assets/acl/bypass-lan-china.acl
core/src/main/assets/acl/gfwlist.acl

raw.githubusercontent.com is polluted to 0.0.0.0 in some cities, making raw files in github inaccessable when using the builtin bypass route.

Add githubusercontent.com to gfwlist

---

core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt

Check only when the method is in the aead-2022-cipher list.

Fix base64 check

---

buildSrc/src/main/kotlin/Helpers.kt
core/src/main/jni/Android.mk

https://github.com/android/ndk/wiki/Changelog-r26#changes
Since NDK r26, Clang now treats -Wimplicit-function-declaration as an error rather than a warning in C11 and newer.
In the submodules, function `pipe2` in `redsocks.c` from `redsocks` and function `arc4random_addrandom` in `evutil_rand.c` from `libevent` are implicitly declared.

fix implicit-function-declaration error when updating NDK to r26+
